# Generated by Django 4.0.5 on 2022-07-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя автора')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия автора')),
                ('bio', models.TextField(verbose_name='Краткая биография автора')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название серии')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Изображение книги')),
                ('publishing_year', models.PositiveSmallIntegerField(verbose_name='Год публикации книги')),
                ('publishing_house', models.CharField(max_length=150, verbose_name='Издательство')),
                ('format', models.CharField(max_length=150, verbose_name='Формат')),
                ('cover', models.CharField(max_length=150, verbose_name='Тип обложки')),
                ('catalog_add_date', models.DateField(auto_now_add=True)),
                ('in_stock', models.PositiveSmallIntegerField(verbose_name='Количество на складе')),
                ('number_of_sold', models.PositiveIntegerField(default=0, verbose_name='Количество проданных экземпляров')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author', verbose_name='Автор книги')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='Категория')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.genre', verbose_name='Жанр')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.series', verbose_name='Серия')),
            ],
        ),
    ]
